In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [7]:
def generate_samples(centroids,num_samples,deviation):
    x,y=make_blobs(n_samples=num_samples,centers=centroids,cluster_std=deviation)
    x=StandardScaler().fit_transform(x)
    
    return x,y

In [8]:
centroids=[[4,-1],[5,2],[3,3]]
num_samples=1500
deviation=0.5

In [9]:
x,y=generate_samples(centroids,num_samples,deviation)

In [16]:
x

array([[-0.00270522, -1.32907357],
       [-1.67226597,  0.7559588 ],
       [ 0.35638882,  0.66718006],
       ...,
       [-1.13750212,  1.00433695],
       [ 1.55762581,  0.48098149],
       [-0.68087391,  1.19952066]])

In [19]:
y

array([0, 2, 1, ..., 2, 1, 2])

In [20]:
set(y)

{0, 1, 2}

In [22]:
clusterer=DBSCAN(eps=0.3,min_samples=7)

In [23]:
clusterer.fit(x)

DBSCAN(algorithm='auto', eps=0.3, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=7, n_jobs=None, p=None)

In [25]:
labels=clusterer.labels_

In [26]:
labels

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [27]:
set(labels)

{-1, 0, 1}